# Comprobar disponibilidad de la GPU

In [1]:
# 3pps
import torch

print(f"Version de Pytorch: {torch.__version__}")

# Comprobar si la GPU está disponible
if torch.cuda.is_available():
    print("GPU disponible")
    # Obtener el nombre de la GPU
    print(f"Nombre de la GPU: {torch.cuda.get_device_name(0)}")
    # Obtener el número de GPUs
    print(f"Número de GPUs: {torch.cuda.device_count()}")
else:
    print("No se detectó GPU, se usará la CPU")


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dani/Documents/Repositorios publico/curso-pytorch/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/dani/Documents/Repositorios publico/curso-pytorch/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/dani/Documents/Repositorios publico/curso-pytorch/.ve

Version de Pytorch: 2.2.2
No se detectó GPU, se usará la CPU


# Introducción a los tensores

## Crear un tensor

In [2]:
# Tensor escalar
escalar = torch.tensor(7)
escalar

tensor(7)

In [3]:
# Un valor escalar no tiene dimensiones, no tiene rango
escalar.ndim

0

In [4]:
# Obtener el valores del escalar
escalar.item()

7

In [5]:
# Creacion de un vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Creacion de una matriz 
matriz = torch.tensor([[1,2,3], [4,5,6]])
matriz

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
matriz.ndim

2

In [10]:
matriz.shape

torch.Size([2, 3])

In [11]:
# Creacion de un tensor
tensor = torch.tensor([[
    [[1,2,3],
    [4,5,6]],
    [[7,8,9],
    [6,4,3]]
]])
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6]],

         [[7, 8, 9],
          [6, 4, 3]]]])

In [12]:
tensor.ndim

4

In [13]:
tensor.shape

torch.Size([1, 2, 2, 3])

In [14]:
# Tensores aleatorios
tensor_aleatorio = torch.rand((2,3,4))
tensor_aleatorio

tensor([[[0.7315, 0.7036, 0.4462, 0.1433],
         [0.6909, 0.6339, 0.0940, 0.1992],
         [0.3216, 0.2674, 0.4474, 0.3813]],

        [[0.2377, 0.2528, 0.8061, 0.7399],
         [0.2578, 0.1669, 0.8909, 0.7263],
         [0.4010, 0.2280, 0.4493, 0.5748]]])

In [15]:
tensor_aleatorio.ndim, tensor_aleatorio.shape

(3, torch.Size([2, 3, 4]))

In [16]:
# Tensores con ceros y unos
tensores_ceros = torch.zeros((3,4))
tensores_ceros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
tensores_unos = torch.ones((3,4))
tensores_unos

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
# Crear un tensor con un rango de valores
rango = torch.arange(start=0, end=100, step=2)
rango

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
# Crear tensores con la misma dimension de otro tensor
print(f"Shape de 'rango': {rango.shape}")
copia_rango = torch.zeros_like(input=rango)
print(f"Shape de 'copia_rango': {copia_rango.shape}")
copia_rango

Shape de 'rango': torch.Size([50])
Shape de 'copia_rango': torch.Size([50])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

# Problemas entre tensores

En el caso de realizar operaciones entre tensores que no tengan el mismo tipo de dato (data type),
o tengan las dimensiones adecuadas para operar, o no se encuentren en el mismo espacio de memoria de la CPU o GPU,
pueden generar conflictos y errores

# Obtencion de datos de tensores

In [20]:
tensor = torch.rand(size=(2,2,3))
tensor

tensor([[[0.6785, 0.3092, 0.5808],
         [0.1312, 0.6005, 0.6055]],

        [[0.4862, 0.9419, 0.3044],
         [0.6141, 0.1724, 0.7371]]])

In [21]:
print(f"Data type: {tensor.dtype}")
print(f"Shape: {tensor.shape}")
print(f"Device: {tensor.device}")

Data type: torch.float32
Shape: torch.Size([2, 2, 3])
Device: cpu


In [22]:
tensor = torch.rand(size=(2,2,3), dtype=torch.float16)
tensor

tensor([[[0.6182, 0.3872, 0.4619],
         [0.9092, 0.6328, 0.1250]],

        [[0.4951, 0.7109, 0.2578],
         [0.6694, 0.7402, 0.0249]]], dtype=torch.float16)

In [23]:
print(f"Data type: {tensor.dtype}")
print(f"Shape: {tensor.shape}")
print(f"Device: {tensor.device}")

Data type: torch.float16
Shape: torch.Size([2, 2, 3])
Device: cpu


# Agregacion de tensores

In [24]:
tensor = torch.rand(size=(2,3))
tensor

tensor([[0.0704, 0.3993, 0.8154],
        [0.3288, 0.6869, 0.8930]])

In [25]:
tensor.max(dim=0)

torch.return_types.max(
values=tensor([0.3288, 0.6869, 0.8930]),
indices=tensor([1, 1, 1]))

In [26]:
tensor.max(dim=1)

torch.return_types.max(
values=tensor([0.8154, 0.8930]),
indices=tensor([2, 2]))

Tenemos que las columnas están representadas por el eje/dim 0, y las filas por el eje/dim 1

In [27]:
tensor.mean(dim=0), tensor.mean(dim=1)

(tensor([0.1996, 0.5431, 0.8542]), tensor([0.4283, 0.6362]))

In [28]:
torch.mean(tensor, dim=0), torch.mean(tensor, dim=1)

(tensor([0.1996, 0.5431, 0.8542]), tensor([0.4283, 0.6362]))

In [29]:
tensor

tensor([[0.0704, 0.3993, 0.8154],
        [0.3288, 0.6869, 0.8930]])

In [30]:
torch.argmax(tensor, dim=0), tensor.argmax(dim=0)

(tensor([1, 1, 1]), tensor([1, 1, 1]))

In [31]:
tensor.argmax(dim=1)

tensor([2, 2])

In [32]:
tensor

tensor([[0.0704, 0.3993, 0.8154],
        [0.3288, 0.6869, 0.8930]])

In [33]:
tensor[:, tensor.argmax(dim=1)[0]]

tensor([0.8154, 0.8930])

In [34]:
matriz = torch.rand((4,4))
matriz

tensor([[0.0380, 0.9873, 0.3822, 0.0607],
        [0.1410, 0.3361, 0.7345, 0.8650],
        [0.8603, 0.4539, 0.2303, 0.4235],
        [0.6302, 0.5351, 0.6732, 0.6050]])

In [35]:
submatrix_1 = matriz[0::2, 0::2]
submatrix_2 = matriz[0::2, 1::2]
submatrix_3 = matriz[1::2, 0::2]
submatrix_4 = matriz[1::2, 1::2]
submatrices = torch.stack([submatrix_1, submatrix_2, submatrix_3, submatrix_4])
submatrices

tensor([[[0.0380, 0.3822],
         [0.8603, 0.2303]],

        [[0.9873, 0.0607],
         [0.4539, 0.4235]],

        [[0.1410, 0.7345],
         [0.6302, 0.6732]],

        [[0.3361, 0.8650],
         [0.5351, 0.6050]]])

In [36]:
submatrices.shape

torch.Size([4, 2, 2])

In [37]:
submatrix_1, submatrix_2, submatrix_3, submatrix_4

(tensor([[0.0380, 0.3822],
         [0.8603, 0.2303]]),
 tensor([[0.9873, 0.0607],
         [0.4539, 0.4235]]),
 tensor([[0.1410, 0.7345],
         [0.6302, 0.6732]]),
 tensor([[0.3361, 0.8650],
         [0.5351, 0.6050]]))

In [38]:
print(submatrices.shape)
submatrices = submatrices.unsqueeze(dim=0)
submatrices.shape

torch.Size([4, 2, 2])


torch.Size([1, 4, 2, 2])

In [39]:
norm = torch.linalg.matrix_norm(submatrices, ord="fro", dim=(-2, -1))
norm

tensor([[0.9698, 1.1678, 1.1873, 1.2302]])

In [40]:
(0.5262 ** 2 + 0.0480 ** 2 + 0.0578 ** 2 + 0.1393 ** 2) ** (1/2)

0.5494868242278426

In [41]:
(0.2742 ** 2 + 0.6927 ** 2 + 0.9618 ** 2 + 0.0417 ** 2) ** (1/2)

1.217299084038101

In [42]:
submatrices[:, torch.argmax(norm), :, :]

tensor([[[0.3361, 0.8650],
         [0.5351, 0.6050]]])

In [55]:
torch.manual_seed(42)